### ISSUE TITLE
FR: Hook to get both the css and the html before insertion of inline style

### ISSUE THREAD

**Issue by aTom3333** [hendotcat/11tysass#2]
This plug-in is looking great but is missing one feature I'd like.
I want to use PurgeCSS to strip unused CSS when inlining the style. To do that PurgeCSS needs both the CSS and the HTML (to see with CSS declaration are used) so the current plugin hook isn't enough.
The simplest way I see to do that is probably to call a user defined function at line 231: https://github.com/hendotcat/11tysass/blob/fd80ff83177447817c79350a5deba0eaf50ff193/index.ts#L231 with the css and the rehype tree as parameter that returns the modified css. (you probably want to do something a little more smart like only calling the function once for every matches with the same html/css pair but that's the base idea). 
From there users can do what they want with the html tree, including stringifying it if they so choose.
If making the fact that the plugin is using rehype part of the public API a problem, you could stringify the tree yourself and invoke the user defined function with the HTML string, but that's a bit wasteful if the html is going to be reparsed just after

**Comment by hendotcat** [comment]
This is a really great idea and I'm super grateful you've taken the time to post this issue and explain the use case so well. I agree this is important and I like how much thought you've put into how to support it.

It's also the first issue someone's actually posted here, and it's convinced me this plugin might see wider production use by people other than me! And that's motivated me to [set up a bunch of automated testing](https://github.com/hendotcat/11tysass/commit/db7a2460d306f10de5ee47a34ff56a3fafc1c00a) to avoid accidentally breaking the basic functionality with each update.

This is the very next thing I'm going to focus on and I'm totally open to changing the API in the way you've suggested. I'll throw a bunch of time at this and try out a few different ways of solving it and I'll get back to you. Thanks again!

**Comment by hendotcat** [comment]
Was lucky enough to get some time to work on this today! Check out https://github.com/hendotcat/11tysass/pull/3 and let me know if you think it helps with your use case!
